---
- name: TP Handlers - SSH (version Codespaces)
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Installer le paquet openssh-server
      ansible.builtin.package:
        name: openssh-server
        state: present

    - name: Activer le service SSH
      ansible.builtin.service:
        name: ssh
        state: started
        enabled: true

    - name: DÃ©sactiver la connexion root via SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin No'
        state: present
        backup: true
      notify: Restart_sshd

  handlers:
    - name: Restart_sshd
      ansible.builtin.service:
        name: ssh
        state: restarted
